services:
  postgres:
    image: postgres:15
    container_name: postgres-dragoneclipse-cards
    environment:
      POSTGRES_USER: igor
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dragoneclipse
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  mongodb:
    image: mongo
    container_name: mongo-dragoneclipse-game
    environment:
      MONGO_INITDB_ROOT_USERNAME: igor
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: dragoneclipse-game
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data: